packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

allowBuilds:
  '@embedded-postgres/windows-x64': set this to true or false
  mediasoup: set this to true or false

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "argon2"
  - "@embedded-postgres/windows-x64"
  - "electron"
  - "mediasoup"
