import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsIn,
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Max,
  Min,
} from 'class-validator';
import type { AiEventType, MediaSessionStatus, MonitorActionType, ProctoringEventType, Severity } from '@examguard/types';

export class PauseExamDto {
  @IsInt()
  @Min(5)
  @Max(7 * 24 * 3600)
  durationSeconds!: number;

  @IsString()
  @Length(3, 500)
  reason!: string;
}

export class ResumeExamDto {
  @IsString()
  @Length(3, 500)
  reason!: string;
}

export class TerminateExamDto {
  @IsString()
  @Length(3, 500)
  reason!: string;
}

export class SendMessageDto {
  @IsString()
  @Length(1, 500)
  content!: string;
}

export class FlagStudentDto {
  @IsString()
  @Length(1, 1000)
  note!: string;
}

export class CreateProctoringEventDto {
  @IsUUID()
  attemptId!: string;

  @IsIn([
    'FACE_DETECTED', 'FACE_MISSING', 'MULTIPLE_FACES', 'FACE_PARTIALLY_VISIBLE',
    'CAMERA_BLOCKED', 'CAMERA_CONNECTED', 'CAMERA_DISCONNECTED',
    'CAMERA_PERMISSION_GRANTED', 'CAMERA_PERMISSION_DENIED', 'CAMERA_PERMISSION_REVOKED',
    'CAMERA_DEVICE_CHANGED',
    'MIC_CONNECTED', 'MIC_DISCONNECTED', 'MIC_MUTED', 'MIC_UNMUTED',
    'MIC_PERMISSION_GRANTED', 'MIC_PERMISSION_DENIED', 'MIC_PERMISSION_REVOKED',
    'AUDIO_LEVEL', 'SCREEN_CAPTURE_STARTED', 'SCREEN_CAPTURE_STOPPED',
    'SCREEN_PERMISSION_GRANTED', 'SCREEN_PERMISSION_DENIED', 'SCREEN_PERMISSION_REVOKED',
    'DISPLAY_CHANGED', 'MULTIPLE_DISPLAY_DETECTED', 'EXAM_WINDOW_LOST_FOCUS',
    'EXAM_WINDOW_FOCUS_RESTORED', 'NETWORK_LOST', 'NETWORK_RESTORED',
    'MEDIA_SESSION_CREATED', 'MEDIA_CONNECTED', 'MEDIA_DISCONNECTED',
    'MEDIA_RECONNECTING', 'MEDIA_RECONNECTED', 'MEDIA_FAILED',
    'MEDIA_PUBLISHER_CONNECTING', 'MEDIA_PUBLISHER_CONNECTED',
    'MEDIA_PUBLISHER_RECONNECTING', 'MEDIA_PUBLISHER_RECONNECTED',
    'MEDIA_PUBLISHER_DISCONNECTED', 'MEDIA_PUBLISHER_FAILED',
    'TRACK_PUBLISHED', 'TRACK_UNPUBLISHED',
  ] as ProctoringEventType[])
  type!: ProctoringEventType;

  @IsOptional()
  @IsIn(['INFO', 'WARNING', 'CRITICAL'] as Severity[])
  severity?: Severity;

  @IsOptional()
  detail?: Record<string, unknown>;

  // Idempotency key generated by the client (desktop event queue). When present
  // and already stored, the ingest is a no-op returning the existing event.
  @IsOptional()
  @IsString()
  @Length(8, 120)
  clientEventId?: string;
}

export class UpdateMediaSessionDto {
  @IsUUID()
  attemptId!: string;

  @IsIn(['CAMERA', 'MICROPHONE', 'SCREEN'] as const)
  kind!: 'CAMERA' | 'MICROPHONE' | 'SCREEN';

  @IsIn(['CONNECTING', 'ACTIVE', 'PAUSED', 'ENDED', 'FAILED'] as MediaSessionStatus[])
  status!: MediaSessionStatus;

  @IsOptional()
  @IsBoolean()
  muted?: boolean;

  @IsOptional()
  @IsNumber()
  @Min(0)
  @Max(1)
  audioLevel?: number;
}

export class CreateAiEventDto {
  @IsUUID()
  attemptId!: string;

  @IsIn([
    'FACE_MISSING', 'MULTIPLE_FACES', 'PHONE_DETECTED', 'BOOK_DETECTED', 'PAPER_DETECTED',
    'SECOND_PERSON', 'CAMERA_BLOCKED', 'LOOKING_AWAY', 'UNAUTHORIZED_OBJECT',
    'ENVIRONMENT_CHANGE', 'FACE_PARTIALLY_VISIBLE',
  ] as AiEventType[])
  eventType!: AiEventType;

  @IsNumber()
  @Min(0)
  @Max(1)
  confidence!: number;

  @IsOptional()
  @IsString()
  evidenceRef?: string;

  @IsOptional()
  @IsString()
  modelVersion?: string;
}

export class ReviewAiEventDto {
  @IsIn(['DISMISSED', 'CONFIRMED', 'FLAGGED'] as const)
  status!: 'DISMISSED' | 'CONFIRMED' | 'FLAGGED';
}

export class BatchProctoringEventsDto {
  @IsArray()
  @ArrayMaxSize(50)
  events!: Array<{ type: string; severity?: string; detail?: Record<string, unknown> }>;
}

export class MonitorActionDto {
  @IsOptional()
  @IsIn(['PAUSE', 'RESUME', 'TERMINATE', 'MESSAGE', 'FLAG', 'NOTE'] as MonitorActionType[])
  action?: MonitorActionType;
}